source 'https://rubygems.org'

gem 'net-ping', '~> 5.0'
gem 'whois', '~> 5.0'
gem 'net-dns', '~> 0.9'
gem 'pastel', '~> 0.8'
gem 'tty-prompt', '~> 0.21'

group :development, :test do
  gem 'rspec', '~> 3.13'
  gem 'rubocop', '~> 1.60'
end
