#!/usr/bin/env bash
# AURA OS ISO Builder
# Genera una ISO booteable de Arch Linux con AURA OS preconfigurado.

set -euo pipefail

ISO_NAME="aura-os"
ISO_DIR="${HOME}/${ISO_NAME}-iso"
WORK_DIR="${ISO_DIR}/work"
OUTPUT_DIR="${ISO_DIR}/output"
ARCHISO_DIR="${ISO_DIR}/archiso"

echo "[+] Creando estructura de build..."
mkdir -p "${WORK_DIR}" "${OUTPUT_DIR}" "${ARCHISO_DIR}"

echo "[+] Instalando archiso base..."
if ! command -v mkarchiso &>/dev/null; then
    echo "[!] Instalando archiso..."
    sudo pacman -S --noconfirm archiso
fi

echo "[+] Copiando configuración base..."
cp -r /usr/share/archiso/configs/releng/* "${ARCHISO_DIR}/"

echo "[+] Inyectando AURA OS..."
mkdir -p "${ARCHISO_DIR}/airootfs/etc/aura"
mkdir -p "${ARCHISO_DIR}/airootfs/opt/aura"
mkdir -p "${ARCHISO_DIR}/airootfs/etc/systemd/system"

# Copiar archivos de AURA
cp -r "${HOME}/AURA/backend" "${ARCHISO_DIR}/airootfs/opt/aura/"
cp -r "${HOME}/AURA/scripts" "${ARCHISO_DIR}/airootfs/opt/aura/"
cp -r "${HOME}/AURA/godot" "${ARCHISO_DIR}/airootfs/opt/aura/"
cp "${HOME}/AURA/aura-os/systemd/"*.service "${ARCHISO_DIR}/airootfs/etc/systemd/system/"
cp "${HOME}/AURA/aura-os/systemd/"*.target "${ARCHISO_DIR}/airootfs/etc/systemd/system/"

# Copiar bootstrap
cp "${HOME}/AURA/aura-os/bootstrap/bootstrap_aura_os.py" "${ARCHISO_DIR}/airootfs/root/"

# Configurar profile
cat > "${ARCHISO_DIR}/profiledef.sh" << 'PROFILE'
#!/bin/bash
profile_name="AURA OS"
profile_version="1.0"
ISO_NAME="aura-os"
ISO_VERSION="1.0"
ISO_LABEL="AURA_OS"
PROFILE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PACKAGES=(
    base
    linux
    linux-firmware
    hyprland
    wayland
    waybar
    rofi-wayland
    kitty
    pipewire
    pipewire-pulse
    python
    python-pip
    git
    ufw
    brightnessctl
    postgresql
    redis
)
PROFILE_PACKAGES=()
PROFILE_SYSTEMD=()
PROFILE_HOOKS=()
PROFILE_BOOTLOADER="grub"
PROFILE_KERNEL="linux"
PROFILE_KERNEL_CMDLINE=""
PROFILE_PATCHED_KERNEL=false
PROFILE_XFS=false
PROFILE_BTRFS=false
PROFILE_LUKS=false
PROFILE_LVM=false
PROFILE_MOUNT_POINTS=()
PROFILE_FASTBOOT=false
PROFILE_NETWORK=false
PROFILE_REFLECTOR=false
PROFILE_PACMAN_CACHE=false
PROFILE_PACMAN_HOOKS=false
PROFILE_SKIP_MIRRORLIST=false
PROFILE_CLEAN=false
PROFILE_COMPRESSION="xz"
PROFILE_COMPRESSION_OPTIONS="-Xbcj x86-64"
PROFILE_IMAGE_TYPE="iso"
PROFILE_BOOT_MODE="bios"
PROFILE_GRUB_THEME=""
PROFILE_GRUB_TIMEOUT=5
PROFILE_GRUB_CMDLINE_LINUX_DEFAULT="quiet splash"
PROFILE_GRUB_CMDLINE_LINUX=""
PROFILE_GRUB_CMDLINE_LINUX_RECOVERY=""
PROFILE_GRUB_CMDLINE_LINUX_SERIAL=""
PROFILE_GRUB_CMDLINE_LINUX_SERIAL_RECOVERY=""
PROFILE_GRUB_CMDLINE_LINUX_DEFAULT_SERIAL=""
PROFILE_GRUB_CMDLINE_LINUX_DEFAULT_SERIAL_RECOVERY=""
PROFILE_GRUB_CMDLINE_LINUX_DEFAULT_SERIAL_RECOVERY2=""
PROFILE_GRUB_CMDLINE_LINUX_DEFAULT_SERIAL_RECOVERY3=""
PROFILE_GRUB_CMDLINE_LINUX_DEFAULT_SERIAL_RECOVERY4=""
PROFILE_GRUB_CMDLINE_LINUX_DEFAULT_SERIAL_RECOVERY5=""
PROFILE_GRUB_CMDLINE_LINUX_DEFAULT_SERIAL_RECOVERY6=""
PROFILE_GRUB_CMDLINE_LINUX_DEFAULT_SERIAL_RECOVERY7=""
PROFILE_GRUB_CMDLINE_LINUX_DEFAULT_SERIAL_RECOVERY8=""
PROFILE_GRUB_CMDLINE_LINUX_DEFAULT_SERIAL_RECOVERY9=""
PROFILE_GRUB_CMDLINE_LINUX_DEFAULT_SERIAL_RECOVERY10=""
PROFILE_GRUB_CMDLINE_LINUX_DEFAULT_SERIAL_RECOVERY11=""
PROFILE_GRUB_CMDLINE_LINUX_DEFAULT_SERIAL_RECOVERY12=""
PROFILE_GRUB_CMDLINE_LINUX_DEFAULT_SERIAL_RECOVERY13=""
PROFILE_GRUB_CMDLINE_LINUX_DEFAULT_SERIAL_RECOVERY14=""
PROFILE_GRUB_CMDLINE_LINUX_DEFAULT_SERIAL_RECOVERY15=""
PROFILE_GRUB_CMDLINE_LINUX_DEFAULT_SERIAL_RECOVERY16=""
PROFILE_GRUB_CMDLINE_LINUX_DEFAULT_SERIAL_RECOVERY17=""
PROFILE_GRUB_CMDLINE_LINUX_DEFAULT_SERIAL_RECOVERY18=""
PROFILE_GRUB_CMDLINE_LINUX_DEFAULT_SERIAL_RECOVERY19=""
PROFILE_GRUB_CMDLINE_LINUX_DEFAULT_SERIAL_RECOVERY20=""
PROFILE_GRUB_CMDLINE_LINUX_DEFAULT_SERIAL_RECOVERY21=""
PROFILE_GRUB_CMDLINE_LINUX_DEFAULT_SERIAL_RECOVERY22=""
PROFILE_GRUB_CMDLINE_LINUX_DEFAULT_SERIAL_RECOVERY23=""
PROFILE_GRUB_CMDLINE_LINUX_DEFAULT_SERIAL_RECOVERY24=""
PROFILE_GRUB_CMDLINE_LINUX_DEFAULT_SERIAL_RECOVERY25=""
PROFILE_GRUB_CMDLINE_LINUX_DEFAULT_SERIAL_RECOVERY26=""
PROFILE_GRUB_CMDLINE_LINUX_DEFAULT_SERIAL_RECOVERY27=""
PROFILE_GRUB_CMDLINE_LINUX_DEFAULT_SERIAL_RECOVERY28=""
PROFILE_GRUB_CMDLINE_LINUX_DEFAULT_SERIAL_RECOVERY29=""
PROFILE_GRUB_CMDLINE_LINUX_DEFAULT_SERIAL_RECOVERY30=""
PROFILE_GRUB_CMDLINE_LINUX_DEFAULT_SERIAL_RECOVERY31=""
PROFILE_GRUB_CMDLINE_LINUX_DEFAULT_SERIAL_RECOVERY32=""
PROFILE_GRUB_CMDLINE_LINUX_DEFAULT_SERIAL_RECOVERY33=""
PROFILE_GRUB_CMDLINE_LINUX_DEFAULT_SERIAL_RECOVERY34=""
PROFILE_GRUB_CMDLINE_LINUX_DEFAULT_SERIAL_RECOVERY35=""
PROFILE_GRUB_CMDLINE_LINUX_DEFAULT_SERIAL_RECOVERY36=""
PROFILE_GRUB_CMDLINE_LINUX_DEFAULT_SERIAL_RECOVERY37=""
PROFILE_GRUB_CMDLINE_LINUX_DEFAULT_SERIAL_RECOVERY38=""
PROFILE_GRUB_CMDLINE_LINUX_DEFAULT_SERIAL_RECOVERY39=""
PROFILE_GRUB_CMDLINE_LINUX_DEFAULT_SERIAL_RECOVERY40=""
PROFILE_GRUB_CMDLINE_LINUX_DEFAULT_SERIAL_RECOVERY41=""
PROFILE_GRUB_CMDLINE_LINUX_DEFAULT_SERIAL_RECOVERY42=""
PROFILE_GRUB_CMDLINE_LINUX_DEFAULT_SERIAL_RECOVERY43=""
PROFILE_GRUB_CMDLINE_LINUX_DEFAULT_SERIAL_RECOVERY44=""
PROFILE_GRUB_CMDLINE_LINUX_DEFAULT_SERIAL_RECOVERY45=""
PROFILE_GRUB_CMDLINE_LINUX_DEFAULT_SERIAL_RECOVERY46=""
PROFILE_GRUB_CMDLINE_LINUX_DEFAULT_SERIAL_RECOVERY47=""
PROFILE_GRUB_CMDLINE_LINUX_DEFAULT_SERIAL_RECOVERY48=""
PROFILE_GRUB_CMDLINE_LINUX_DEFAULT_SERIAL_RECOVERY49=""
PROFILE_GRUB_CMDLINE_LINUX_DEFAULT_SERIAL_RECOVERY50=""
PROFILE
echo "[+] Construyendo ISO..."
mkarchiso -v "${ARCHISO_DIR}"
echo "[+] ISO generada en: ${OUTPUT_DIR}/"
ls -lh "${OUTPUT_DIR}/"
