import sys
sys.path.insert(0, 'ARIA_APP/backend')
import os
from dotenv import load_dotenv
load_dotenv('ARIA_APP/backend/.env')
token = os.getenv('GITHUB_TOKEN')
if not token:
    raise RuntimeError("GITHUB_TOKEN environment variable is required. Set it before running this script.")
from github import Github
gh = Github(token)

repo = gh.get_repo('raidenia3-oss/ARIA')

issues = [
    {
        'title': 'Research: Integrate Candle.rs for local LLM inference (from oxide-lab/Oxide-Lab)',
        'body': '## Source Repository\n**oxide-lab/Oxide-Lab** \u2b50116 \u2014 Modern desktop app (Rust + Tauri v2 + Svelte 5 + Candle/HF)\n\n## Why This Matters for ARIA\n- **Exact tech stack match**: Tauri v2 + local LLM inference via Candle.rs\n- **GPU acceleration**: Vulkan/Metal/CUDA support for local inference\n- **Zero telemetry**: Fully offline, privacy-first architecture\n- **GGUF model support**: Native llama.cpp compatible formats\n\n## Integration Plan\n1. Add `candle-core`, `candle-nn`, `candle-transformers` to Cargo.toml\n2. Implement model loading for GGUF/SafeTensors formats\n3. Add Vulkan/Metal/CUDA device detection\n4. Create Rust Tauri commands for inference\n5. Replace Ollama HTTP calls with in-process inference\n\n## Reference Code Patterns\n```rust\n// From oxide-lab/Oxide-Lab\nuse candle::{Device, Tensor, DType};\nuse candle_nn::VarBuilder;\nuse candle_transformers::models::llama::{Model, Config};\n\nlet device = Device::new_cuda(0)?; // or Metal/Vulkan\nlet model = Model::load_from_safetensors(&var_builder, &config)?;\n```\n\n## Acceptance Criteria\n- [ ] Candle.rs integrated in Tauri backend\n- [ ] GGUF model loading working\n- [ ] GPU acceleration detected and used\n- [ ] Inference latency < 2s for 7B model\n- [ ] Memory usage < 8GB for 7B model\n\n## Related Research\nSee: `ARIA_APP/github_research_report.md` (Tier 1, Item 3)',
        'labels': ['research', 'integration', 'tauri', 'local-llm', 'rust', 'high-priority']
    },
    {
        'title': 'Research: Replace Vosk with Whisper.cpp for STT (from rlucio01/whisper-app)',
        'body': '## Source Repository\n**rlucio01/whisper-app** \u2b504 \u2014 Tauri + React + Rust + Whisper.cpp local STT\n\n## Why This Matters for ARIA\n- **Better accuracy**: Whisper.cpp >> Vosk for multilingual/accented speech\n- **GPU acceleration**: Intel/AMD/CUDA GPU selection support\n- **LLM reformatting**: Post-process transcriptions with context-aware LLM\n- **Tauri native**: Built for same stack as ARIA v5\n\n## Integration Plan\n1. Add `whisper-rs` crate to Tauri backend\n2. Download Whisper models (tiny/base/small/medium/large)\n3. Implement GPU backend selection (CUDA/Metal/Vulkan/CPU)\n4. Add streaming transcription support\n5. Replace Vosk wake word + STT pipeline\n\n## Reference Code Patterns\n```rust\n// From rlucio01/whisper-app\nuse whisper_rs::{FullParams, SamplingStrategy, WhisperContext};\nlet ctx = WhisperContext::new_with_params(&model_path, params)?;\nlet mut state = ctx.create_state()?;\nstate.full(params, &audio_samples)?;\nlet text = state.get_segment_text(0)?;\n```\n\n## Acceptance Criteria\n- [ ] Whisper.cpp integrated in Tauri backend\n- [ ] Model auto-download (tiny/base/small)\n- [ ] GPU acceleration working\n- [ ] WER < 10% on Spanish/English test set\n- [ ] Real-time factor < 0.5x\n\n## Related Research\nSee: `ARIA_APP/github_research_report.md` (Tier 2, Item 5)',
        'labels': ['research', 'integration', 'stt', 'whisper', 'tauri', 'high-priority']
    },
    {
        'title': 'Research: Integrate Piper TTS for offline neural TTS (from kleenpulse/companion-tts)',
        'body': '## Source Repository\n**kleenpulse/companion-tts** \u2b502 \u2014 Floating desktop companion with Piper TTS + Tauri\n\n## Why This Matters for ARIA\n- **Offline neural TTS**: Piper TTS runs completely locally\n- **Multiple backends**: ElevenLabs, Mistral, offline Piper, Windows TTS\n- **Real-time streaming**: Low-latency audio streaming\n- **Floating orb UI**: Companion pattern matches ARIA\u2019s orb visualizer\n\n## Integration Plan\n1. Add `piper-tts` crate or use `piper` Python bindings\n2. Download Piper voices (es_MX, en_US, etc.)\n3. Implement streaming audio playback\n4. Create Tauri commands for TTS synthesis\n5. Add voice selection UI in settings\n\n## Reference Code Patterns\n```rust\n// From kleenpulse/companion-tts (TypeScript + Rust)\n// Piper TTS via command line or library\npiper --model es_MX-clara-low.onnx --output_file output.wav "Hola mundo"\n```\n\n## Acceptance Criteria\n- [ ] Piper TTS integrated\n- [ ] At least 2 voices (ES/EN) working\n- [ ] Streaming playback < 200ms latency\n- [ ] CPU usage < 50% during synthesis\n- [ ] Voice selection in settings UI\n\n## Related Research\nSee: `ARIA_APP/github_research_report.md` (Tier 2, Item 6)',
        'labels': ['research', 'integration', 'tts', 'piper', 'tauri', 'high-priority']
    },
    {
        'title': 'Research: Implement global hotkey system (from Vinay7766/quickno, TryBuddyAI/BuddyOS)',
        'body': '## Source Repositories\n- **Vinay7766/quickno** \u2b5022 \u2014 Lightning-fast AI search with global hotkeys (Tauri + Windows)\n- **TryBuddyAI/BuddyOS** \u2b500 \u2014 Hotkey-summoned glass mascot (Tauri + Three.js + React)\n\n## Why This Matters for ARIA\n- **Core UX feature**: Hotkey summon is primary ARIA interaction\n- **Windows optimization**: quickno is Windows-specific\n- **Three.js orb integration**: BuddyOS shows orb + hotkey pattern\n- **System tray integration**: Background daemon with hotkey listener\n\n## Integration Plan\n1. Use `tauri-plugin-global-shortcut` or `global-hotkey` crate\n2. Register `Ctrl+Space` (or configurable) for orb summon\n3. Implement system tray with show/hide/quit\n4. Add hotkey customization in settings\n5. Ensure low-latency orb animation on summon\n\n## Reference Code Patterns\n```rust\n// Tauri 2.0 global shortcut\ntauri::Manager::global_shortcut_manager()\n    .register("Ctrl+Space", move || {\n        window.show();\n        window.set_focus();\n    })?;\n```\n\n## Acceptance Criteria\n- [ ] Global hotkey registered and working\n- [ ] Orb animates on summon (< 100ms)\n- [ ] System tray icon with menu\n- [ ] Hotkey configurable in settings\n- [ ] Works when app is minimized/trayed\n\n## Related Research\nSee: `ARIA_APP/github_research_report.md` (Tier 2, Items 7 & 4)',
        'labels': ['research', 'integration', 'hotkey', 'tauri', 'ux', 'high-priority']
    },
    {
        'title': 'Research: Vector-based long-term memory via MCP (from CaviraOSS/LongMemory)',
        'body': '## Source Repository\n**CaviraOSS/LongMemory** \u2b504,511 \u2014 Local persistent memory store for LLM apps\n\n## Why This Matters for ARIA\n- **Current limitation**: SQLite memory is basic key-value\n- **Vector search**: Semantic retrieval for conversations/knowledge\n- **MCP server**: Standardized interface for any LLM client\n- **Works with**: Claude Desktop, Copilot, Codex, custom agents\n\n## Integration Plan\n1. Deploy LongMemory as MCP server (stdio or HTTP)\n2. Integrate with ARIA\u2019s memory system via MCP client\n3. Migrate from SQLite to vector embeddings (BGE-M3/Qdrant)\n4. Add semantic search for conversation history\n5. Implement memory consolidation/summarization\n\n## Reference Architecture\n```\nARIA Agent \u2192 MCP Client \u2192 LongMemory MCP Server \u2192 Qdrant Vector DB\n                    \u2193\n            Embeddings (BGE-M3)\n            Semantic Search\n            Memory Retrieval\n```\n\n## Acceptance Criteria\n- [ ] LongMemory MCP server running\n- [ ] ARIA connects via MCP protocol\n- [ ] Vector embeddings for conversations\n- [ ] Semantic search returning relevant memories\n- [ ] Memory consolidation running periodically\n\n## Related Research\nSee: `ARIA_APP/github_research_report.md` (Tier 2, Item 8)',
        'labels': ['research', 'integration', 'memory', 'mcp', 'vector-db', 'high-priority']
    },
    {
        'title': 'Research: Windows Computer Use via MCP (from sandraschi/windows-computer-use-mcp)',
        'body': '## Source Repository\n**sandraschi/windows-computer-use-mcp** \u2b5040 \u2014 Windows Computer Use MCP server (22 tools)\n\n## Why This Matters for ARIA\n- **Computer Use capability**: ARIA can control desktop apps\n- **22 MCP tools**: click, type, screenshot, OCR, UI inspection, window management\n- **Autonomous mission engine**: Macro recorder, intent-based discovery\n- **Tauri desktop app**: Same stack, ships as MCP server + web UI + desktop app\n\n## Integration Plan\n1. Deploy windows-computer-use-mcp as MCP server\n2. Connect ARIA via MCP client (stdio)\n3. Expose computer use tools to ARIA\u2019s skill system\n4. Add safety/approval layer for destructive actions\n5. Implement intent-based task execution\n\n## MCP Tools Available\n- `click`, `type`, `scroll`, `drag`\n- `screenshot`, `ocr`, `ui_inspect`\n- `window_list`, `window_focus`, `window_bounds`\n- `keyboard_send`, `mouse_move`\n- `macro_record`, `macro_playback`\n- `autonomous_mission`, `intent_discovery`\n\n## Acceptance Criteria\n- [ ] MCP server connected to ARIA\n- [ ] All 22 tools callable from ARIA skills\n- [ ] Safety approval for destructive actions\n- [ ] Screenshot + OCR working\n- [ ] Autonomous mission execution tested\n\n## Related Research\nSee: `ARIA_APP/github_research_report.md` (Tier 3, Item 11)',
        'labels': ['research', 'integration', 'computer-use', 'mcp', 'automation', 'windows', 'medium-priority']
    },
    {
        'title': 'Research: Self-improving agent patterns (from Garrus800-stack/genesis-agent)',
        'body': '## Source Repository\n**Garrus800-stack/genesis-agent** \u2b5041 \u2014 Self-aware, self-modifying cognitive agent\n\n## Why This Matters for ARIA\n- **Self-modification**: Reads and modifies its own code\n- **Autonomous planning**: Plans and executes without human intervention\n- **Episodic memory**: Remembers across sessions (Obsidian vault bridge)\n- **Emotional state**: Trust levels, emotional modeling\n- **MCP server & client**: Standardized tool interface\n\n## Integration Plan\n1. Study genesis-agent\u2019s self-modification patterns\n2. Implement code introspection in ARIA\u2019s self-improvement skill\n3. Add episodic memory with vector storage\n4. Create autonomous planning loop\n5. Add trust/confidence scoring for self-changes\n\n## Key Patterns to Adopt\n- **Code reading**: Agent reads its own source files\n- **Code verification**: Tests changes before committing\n- **Dreaming**: Idle-time background processing\n- **Obsidian bridge**: Human-readable memory export\n\n## Acceptance Criteria\n- [ ] ARIA can read its own codebase\n- [ ] Self-modification proposals generated\n- [ ] Automated testing of proposed changes\n- [ ] Episodic memory persistence\n- [ ] Trust scoring for autonomous changes\n\n## Related Research\nSee: `ARIA_APP/github_research_report.md` (Tier 4, Item 12)',
        'labels': ['research', 'integration', 'self-improvement', 'autonomous', 'cognitive', 'medium-priority']
    },
    {
        'title': 'Research: Three.js orb enhancements (from TryBuddyAI/BuddyOS)',
        'body': '## Source Repository\n**TryBuddyAI/BuddyOS** \u2014 Desktop AI companion with Three.js orb (Tauri + React + Three.js)\n\n## Why This Matters for ARIA\n- **Exact stack match**: Tauri + React 19 + Three.js (ARIA v5)\n- **Glass mascot UI**: Hotkey-summoned floating orb\n- **Visual personality**: Orb as primary interaction surface\n- **Marketing site + desktop app**: Complete product pattern\n\n## Integration Plan\n1. Analyze BuddyOS orb visualization code\n2. Enhance ARIA\u2019s OrbVisual.tsx with:\n   - Particle systems (8-12 orbital particles)\n   - Rotating rings (primary + secondary)\n   - Glow/halo effects\n   - Pulse/burst animations on speech\n   - Color scheme: Serpentinum \u00d7 Caelestia\n3. Add interaction states: idle, listening, thinking, speaking\n4. Implement hotkey summon animation\n\n## Reference: ARIA\u2019s Current Orb (7-layer)\n1. Burst effect\n2. Solid core 60px radial gradient\n3. Main ring glow\n4. 8-12 orbital particles\n5. Rotating secondary ring 35px\n6. Outer halo 30px blur\n7. Expanding pulse ring 50-60px\n\n## Acceptance Criteria\n- [ ] Orb visual parity with BuddyOS quality\n- [ ] 60fps on integrated graphics\n- [ ] State transitions smooth (idle\u2192listening\u2192thinking\u2192speaking)\n- [ ] Hotkey summon animation < 200ms\n- [ ] Color scheme matches design system\n\n## Related Research\nSee: `ARIA_APP/github_research_report.md` (Tier 1, Item 4)',
        'labels': ['research', 'integration', 'threejs', 'orb', 'ui', 'tauri', 'medium-priority']
    },
    {
        'title': 'Research: MCP plugin system (from Helix, 5ire, Pinvou-agent)',
        'body': '## Source Repositories\n- **tjcrims0nx/Helix** \u2b5010 \u2014 Tauri + Vue 3 + llama.cpp + MCP plugin system\n- **nanbingxyz/5ire** \u2b505,358 \u2014 MCP client desktop AI assistant\n- **Pinvou/pinvou-agent** \u2b502,128 \u2014 Desktop AI agent with MCP + skill marketplace\n\n## Why This Matters for ARIA\n- **Extensibility**: Plugins for tools, skills, providers\n- **Standardization**: MCP as universal plugin protocol\n- **Skill marketplace**: Community-contributed capabilities\n- **Hot-reload**: Dynamic plugin loading without restart\n\n## Integration Plan\n1. Define ARIA MCP plugin manifest schema\n2. Implement MCP server in Tauri backend\n3. Create plugin loader with hot-reload\n4. Build skill marketplace UI\n5. Migrate existing skills to MCP tools\n\n## Plugin Manifest Schema\n```json\n{\n  "name": "aria-skill-web-search",\n  "version": "1.0.0",\n  "mcp": {\n    "tools": [\n      {"name": "search", "description": "Web search", "inputSchema": {...}}\n    ]\n  },\n  "entry": "dist/index.js",\n  "permissions": ["network", "storage"]\n}\n```\n\n## Acceptance Criteria\n- [ ] MCP server running in Tauri backend\n- [ ] Plugin loader with hot-reload\n- [ ] At least 3 skills migrated to MCP tools\n- [ ] Plugin marketplace UI functional\n- [ ] Community plugin installation working\n\n## Related Research\nSee: `ARIA_APP/github_research_report.md` (Tier 1 Items 1,2 + Tier 4 Item 14)',
        'labels': ['research', 'integration', 'mcp', 'plugins', 'extensibility', 'medium-priority']
    },
    {
        'title': 'Research: Multi-agent swarms (from HashCortX, Pinvou-agent)',
        'body': '## Source Repositories\n- **Hash-7777/HashCortX** \u2b50153 \u2014 Local-first AI workspace with multi-agent swarms\n- **Pinvou/pinvou-agent** \u2b502,128 \u2014 Multi-agent desktop AI with skill marketplace\n\n## Why This Matters for ARIA\n- **Current**: Single agent with skills\n- **Future**: Swarm of specialized agents collaborating\n- **No backend**: Fully local, peer-to-peer agent communication\n- **3D visualization**: Agent swarms in Three.js space\n\n## Integration Plan\n1. Design agent communication protocol (MCP-based)\n2. Implement agent spawning/lifecycle management\n3. Create swarm coordinator for task decomposition\n4. Add 3D visualization of agent swarm in orb\n5. Implement consensus/voting for decisions\n\n## Swarm Architecture\n```\nUser Request\n    \u2193\nSwarm Coordinator (decomposes task)\n    \u2193\nAgent 1: Research \u2192 Agent 2: Code \u2192 Agent 3: Test \u2192 Agent 4: Review\n    \u2193\nConsensus \u2192 Result\n```\n\n## Acceptance Criteria\n- [ ] Multiple agents can spawn and communicate\n- [ ] Task decomposition working\n- [ ] Swarm visualization in Three.js orb\n- [ ] Consensus mechanism implemented\n- [ ] Benchmark: 3-agent swarm > single agent on complex tasks\n\n## Related Research\nSee: `ARIA_APP/github_research_report.md` (Tier 4, Items 13 & 1)',
        'labels': ['research', 'integration', 'multi-agent', 'swarm', 'architecture', 'low-priority']
    },
    {
        'title': 'Feature: WebGPU Phase 2 — Post-processing & Compute Shaders',
        'body': '## Objective\nImplement advanced WebGPU post-processing effects and compute shader pipelines for the orb visualization and HUD.\n\n## Scope\n1. Bloom/glow post-processing pass (HDR)\n2. Particle systems via compute shaders for orbital particles\n3. Real-time fluid simulation behind the orb (Smoothed Particle Hydrodynamics)\n4. Tone mapping — Serpantineum × Caelestia color palette\n5. WebGPU compute for brain orchestration state visualization\n\n## Reference\n- `v5/src/components/OrbVisual/OrbVisual.tsx` current implementation\n- `v5/src/components/OrbVisual/BackgroundShader.tsx` for shader patterns\n\n## Acceptance Criteria\n- [ ] Bloom post-processing pass (Three.js WebGLRenderer.toneMapping)\n- [ ] Compute shader particle system (8-12 orbital particles)\n- [ ] 60fps on integrated graphics\n- [ ] Color palette matches design system\n',
        'labels': ['feature', 'webgpu', 'threejs', 'graphics', 'ui']
    },
    {
        'title': 'Feature: Self-Improvement Loop Automation',
        'body': '## Objective\nImplement an autonomous self-improvement loop that continuously evaluates, proposes, tests, and commits code changes.\n\n## Architecture\n```\n1. Evaluate: Run test suite + lint\n2. Plan: Identify failing tests / code quality issues\n3. Propose: Generate patches via Ollama\n4. Test: Run relevant tests on proposed changes\n5. Merge: Commit only if tests pass\n6. Reflect: Update improvement_state.json\n```\n\n## Integration Points\n- `backend/evolution/engine.py` — orchestrator\n- `backend/proactive/engine.py` — proactive task scheduling\n- `ai_providers.py` — Ollama for code generation\n- `ARIA_APP/memory/` — persistent improvement state\n\n## Acceptance Criteria\n- [ ] Automated test → patch → merge loop\n- [ ] Improvement state persisted in JSON\n- [ ] At least 1 improvement per 24h (auto or proposed)\n- [ ] Safety: no breaking changes without human approval\n',
        'labels': ['feature', 'self-improvement', 'automation', 'evolution', 'medium-priority']
    }
]

for issue_data in issues:
    try:
        issue = repo.create_issue(
            title=issue_data['title'],
            body=issue_data['body'],
            labels=issue_data['labels']
        )
        print('Created issue #' + str(issue.number) + ': ' + issue_data['title'][:60] + '...')
    except Exception as e:
        print('Failed: ' + issue_data['title'][:60] + '... - ' + str(e))

print(f'\n✅ All {len(issues)} issues created!')