import pathlib
import sys

def write_file(rel_path: str, content: str) -> None:
    p = pathlib.Path(rel_path)
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(content, encoding='utf-8')
    print(f'OK: {rel_path} ({len(content.splitlines())} lines)')

# ============================================================
# cognitive_graph_extend.py
# ============================================================
cgce = []
cgce.append('# -*- coding: utf-8 -*-')
cgce.append('"""AURA OS - Chunk 3: Cognitive Graph Extend.')
cgce.append('')
cgce.append('Extiende cognitive_graph.py existente.')
cgce.append('CAPA: Cada accion = nuevo nodo + edge.')
cgce.append('Actualizacion en tiempo real del grafo cognitivo.')
cgce.append('"""')
cgce.append('from __future__ import annotations')
cgce.append('')
cgce.append('import json, logging, hashlib, os, time')
cgce.append('from dataclasses import dataclass, field')
cgce.append('from datetime import datetime')
cgce.append('from enum import Enum')
cgce.append('from pathlib import Path')
cgce.append('from typing import Any, Dict, List, Optional, Set')
cgce.append('from collections import deque')
cgce.append('')
cgce.append("logger = logging.getLogger('AURA.CognitiveGraph')")
cgce.append('')
cgce.append("GRAPH_DATA_DIR = Path(os.environ.get('AURA_GRAPH_DIR', 'data/memory/graph'))")
cgce.append("GRAPH_FILE = GRAPH_DATA_DIR / 'cognitive_graph_ext.json'")
cgce.append('')
cgce.append('')
cgce.append('class NodeType(Enum):')
cgce.append('    ACTION = "action"')
cgce.append('    EVENT = "event"')
cgce.append('    DECISION = "decision"')
cgce.append('    PATTERN = "pattern"')
cgce.append('    ENTITY = "entity"')
cgce.append('    RELATIONSHIP = "relationship"')
cgce.append('')
cgce.append('')
cgce.append('class EdgeType(Enum):')
cgce.append('    CAUSES = "causes"')
cgce.append('    PRECEDES = "precedes"')
cgce.append('    FOLLOWS = "follows"')
cgce.append('    RELATED_TO = "related_to"')
cgce.append('    ENABLES = "enables"')
cgce.append('    PREFERS = "prefers"')
cgce.append('')
cgce.append('')
cgce.append('@dataclass')
cgce.append('class GraphNode:')
cgce.append('    node_id: str')
cgce.append('    label: str')
cgce.append('    node_type: NodeType = NodeType.ACTION')
cgce.append('    attributes: Dict[str, Any] = field(default_factory=dict)')
cgce.append('    created_at: float = field(default_factory=time.time)')
cgce.append('    weight: float = 1.0')
cgce.append('    visited: bool = False')
cgce.append('')
cgce.append('    def to_dict(self) -> Dict[str, Any]:')
cgce.append('        return dict(node_id=self.node_id, label=self.label,')
cgce.append('                    node_type=self.node_type.value,')
cgce.append('                    attributes=self.attributes,')
cgce.append('                    created_at=self.created_at,')
cgce.append('                    weight=self.weight)')
cgce.append('')
cgce.append('    @classmethod')
cgce.append('    def from_dict(cls, data: Dict[str, Any]) -> "GraphNode":')
cgce.append('        return cls(node_id=data["node_id"], label=data["label"],')
cgce.append('                   node_type=NodeType(data.get("node_type", "action")),')
cgce.append('                   attributes=data.get("attributes", {}),')
cgce.append('                   created_at=data.get("created_at", time.time()),')
cgce.append('                   weight=data.get("weight", 1.0))')
cgce.append('')
cgce.append('')
cgce.append('@dataclass')
cgce.append('class GraphEdge:')
cgce.append('    source: str')
cgce.append('    target: str')
cgce.append('    edge_type: EdgeType = EdgeType.RELATED_TO')
cgce.append('    weight: float = 1.0')
cgce.append('    attributes: Dict[str, Any] = field(default_factory=dict)')
cgce.append('    created_at: float = field(default_factory=time.time)')
cgce.append('')
cgce.append('    def to_dict(self) -> Dict[str, Any]:')
cgce.append('        return dict(source=self.source, target=self.target,')
cgce.append('                    edge_type=self.edge_type.value,')
cgce.append('                    weight=self.weight,')
cgce.append('                    attributes=self.attributes,')
cgce.append('                    created_at=self.created_at)')
cgce.append('')
cgce.append('    @classmethod')
cgce.append('    def from_dict(cls, data: Dict[str, Any]) -> "GraphEdge":')
cgce.append('        return cls(source=data["source"], target=data["target"],')
cgce.append('                   edge_type=EdgeType(data.get("edge_type", "related_to")),')
cgce.append('                   weight=data.get("weight", 1.0),')
cgce.append('                   attributes=data.get("attributes", {}),')
cgce.append('                   created_at=data.get("created_at", time.time()))')
cgce.append('')
cgce.append('')
cgce.append('class CognitiveGraphExtend:')
cgce.append('    """Extensión del grafo cognitivo para registro de acciones en tiempo real.')
cgce.append('')
cgce.append('    Cada accion se registra como nodo y se conecta con edges a otras')
cgce.append('    acciones, eventos o patrones relacionados.')
cgce.append('')
cgce.append('    Flujo tipico:')
cgce.append('        1. Orchestrator ejecuta una accion')
cgce.append('        2. CognitiveGraphExtend.add_action(action_str, metadata) -> nuevo nodo')
cgce.append('        3. Se conecta con edges a nodos previos relacionados')
cgce.append('        4. Grafo persistente en disco')
cgce.append('')
cgce.append('    Permite:')
cgce.append('        - Consultar historial de acciones')
cgce.append('        - Detectar secuencias comunes (patrones)')
cgce.append('        - Encontrar rutas criticas entre estados')
cgce.append('        - Analisis de dependencias entre componentes')
cgce.append('    """')
cgce.append('')
cgce.append('    def __init__(self, graph_file: Optional[Path] = None):')
cgce.append('        self._graph_file = graph_file or GRAPH_FILE')
cgce.append('        self._nodes: Dict[str, GraphNode] = {}')
cgce.append('        self._edges: Dict[str, GraphEdge] = {}')
cgce.append('        self._edge_index: Dict[str, List[str]] = {}')
cgce.append('        self._adjacency: Dict[str, Set[str]] = {}')
cgce.append('        self._load()')
cgce.append('')
cgce.append('    def _gen_id(self, prefix: str, label: str) -> str:')
cgce.append('        ts = int(time.time() * 1000)')
cgce.append('        h = hashlib.md5(f"{prefix}:{label}:{ts}".encode()).hexdigest()[:8]')
cgce.append('        return f"{prefix}_{h}"')
cgce.append('')
cgce.append('    def add_action(self, action: str,')
cgce.append('                   metadata: Optional[Dict[str, Any]] = None,')
cgce.append('                   weight: float = 1.0) -> str:')
cgce.append('        node_id = self._gen_id("action", action)')
cgce.append('        if node_id in self._nodes:')
cgce.append('            self._nodes[node_id].weight += 1.0')
cgce.append('            return node_id')
cgce.append('        node = GraphNode(node_id=node_id, label=action[:200], node_type=NodeType.ACTION,')
cgce.append('                         attributes={**(metadata or {}), "action_text": action, "timestamp": time.time()},')
cgce.append('                         weight=weight)')
cgce.append('        self._nodes[node_id] = node')
cgce.append('        self._adjacency.setdefault(node_id, set())')
cgce.append('        self._save()')
cgce.append('        logger.debug(f"Graph: Added action node {node_id}: {action[:50]}")')
cgce.append('        return node_id')
cgce.append('')
cgce.append('    def add_event(self, event_type: str,')
cgce.append('                  event_data: Optional[Dict[str, Any]] = None) -> str:')
cgce.append('        if event_data is None: event_data = {}')
cgce.append('        node_id = self._gen_id("event", event_type)')
cgce.append('        node = GraphNode(node_id=node_id,')
cgce.append('                         label=f"{event_type}_{datetime.now().isoformat()[:19]}",')
cgce.append('                         node_type=NodeType.EVENT,')
cgce.append('                         attributes={"event_type": event_type, "data": event_data,')
cgce.append('                                    "timestamp": time.time()})')
cgce.append('        self._nodes[node_id] = node')
cgce
