import pathlib

content = (
    '# -*- coding: utf-8 -*-\n'
    '"""AURA OS - Chunk 2: RAG Agent.\n'
    '\n'
    'Agente de recuperacion de informacion basado en memoria.\n'
    'Integra con MemoryManager para busqueda semantica.\n'
    '"""\n'
    'from __future__ import annotations\n'
    '\n'
    'import logging\n'
    'import time\n'
    'from typing import Any, Dict, List, Optional\n'
    '\n'
    'from backend.memory.memory_manager import get_memory_manager, MemoryManager\n'
    'from backend.core.event_bus import CoreEvent, EventType, get_event_bus\n'
    '\n'
    'logger = logging.getLogger("AURA.RAGAgent")\n'
    '\n'
    '\n'
    'class RAGAgent:\n'
    '    """Agente de recuperacion de informacion en memoria.\n'
    '\n'
    '    Realiza busqueda semantica en los tres niveles de memoria:\n'
    '    - Short term: conversaciones recientes\n'
    '    - Medio term: persistencia de 24h\n'
    '    - Long term: patrones aprendidos\n'
    '    """\n'
    '\n'
    '    def __init__(\n'
    '        self,\n'
    '        memory_manager: Optional[MemoryManager] = None,\n'
    '        event_bus: Optional[Any] = None,\n'
    '        agent_id: str = "rag_agent",\n'
    '    ) -> None:\n'
    '        self._memory = memory_manager or get_memory_manager()\n'
    '        self._bus = event_bus or get_event_bus()\n'
    '        self._agent_id = agent_id\n'
    '        self._last_query_time: float = 0.0\n'
    '        self._query_count: int = 0\n'
    '\n'
    '    async def search(\n'
    '        self,\n'
    '        query: str,\n'
    '        top_k: int = 5,\n'
    '        include_context: bool = True,\n'
    '    ) -> Dict[str, Any]:\n'
    '        """Busca informacion relevante en memoria.\n'
    '\n'
    '        Args:\n'
    '            query: Consulta de busqueda\n'
    '            top_k: Numero maximo de resultados\n'
    '            include_context: Si incluir contexto adicional\n'
    '\n'
    '        Returns:\n'
    '            Dict con resultados y metadata\n'
    '        """\n'
    '        start_time = time.time()\n'
    '        self._query_count += 1\n'
    '\n'
    '        logger.debug(f"RAGAgent: Buscando: {query[:50]}")\n'
    '\n'
    '        try:\n'
    '            context = self._memory.get_context(query, top_k=top_k)\n'
    '\n'
    '            results = {\n'
    '                "query": query,\n'
    '                "results": context,\n'
    '                "total_matches": context.get("total_matches", 0),\n'
    '                "search_time_ms": round((time.time() - start_time) * 1000, 2),\n'
    '                "agent_id": self._agent_id,\n'
    '                "rationale": context.get("rationale", ""),\n'
    '            }\n'
    '\n'
    '            if include_context:\n'
    '                results["context"] = {\n'
    '                    "short_term": context.get("short_term", []),\n'
    '                    "medium_term": context.get("medium_term", []),\n'
    '                    "long_term": context.get("long_term", []),\n'
    '                }\n'
    '\n'
    '            self._last_query_time = time.time()\n'
    '\n'
    '            return results\n'
    '\n'
    '        except Exception as e:\n'
    '            logger.error(f"RAGAgent: Error en busqueda: {e}")\n'
    '            return {\n'
    '                "query": query,\n'
    '                "results": [],\n'
    '                "total_matches": 0,\n'
    '                "search_time_ms": round((time.time() - start_time) * 1000, 2),\n'
    '                "agent_id": self._agent_id,\n'
    '                "error": str(e),\n'
    '            }\n'
    '\n'
    '    async def search_and_respond(self, query: str) -> str:\n'
    '        """Busca y retorna respuesta formateada.\n'
    '\n'
    '        Args:\n'
    '            query: Consulta del usuario\n'
    '\n'
    '        Returns:\n'
    '            Respuesta en texto plano\n'
    '        """\n'
    '        results = await self.search(query, top_k=5)\n'
    '\n'
    '        if not results.get("results", {}).get("total_matches", 0):\n'
    '            return "No encontre informacion relevante en mi memoria."\n'
    '\n'
    '        rationale = results.get("rationale", "")\n'
    '        matches = results["results"].get("total_matches", 0)\n'
    '\n'
    '        response = f"Encontre {matches} coincidencia(s): {rationale}."\n'
    '\n'
    '        short_term = results["results"].get("short_term", [])\n'
    '        for item in short_term[:3]:\n'
    '            response += f"\n  - [{item["role"]}] {item["content"][:100]}"\n'
    '\n'
    '        return response\n'
    '\n'
    '    def get_status(self) -> Dict[str, Any]:\n'
    '        """Retorna estado del agente."""\n'
    '        return {\n'
    '            "agent_id": self._agent_id,\n'
    '            "query_count": self._query_count,\n'
    '            "last_query_time": self._last_query_time,\n'
    '            "memory_sources": ["short_term", "medium_term", "long_term"],\n'
    '        }\n'
    '\n'
    '\n'
    'def get_rag_agent() -> RAGAgent:\n'
    '    """Retorna instancia global del RAGAgent."""\n'
    '    if not hasattr(get_rag_agent, "_instance"):\n'
    '        get_rag_agent._instance = RAGAgent()\n'
    '    return get_rag_agent._instance\n'
    '\n'
    '\n'
    'def reset_rag_agent() -> None:\n'
    '    """Resetea la instancia global."""\n'
    '    if hasattr(get_rag_agent, "_instance"):\n'
    '        delattr(get_rag_agent, "_instance")\n'
    '\n'
    '\n'
    'if __name__ == "__main__":\n'
    '    import asyncio\n'
    '\n'
    '    async def test():\n'
    '        agent = get_rag_agent()\n'
    '        results = await agent.search("Hola")\n'
    '        print(f"RAGAgent: {results["total_matches"]} resultados")\n'
    '        print(agent.get_status())\n'
    '        print("rag_agent.py OK")\n'
    '\n'
    '    asyncio.run(test())\n'
)

path = pathlib.Path('C:/Users/User/Downloads/AURA/backend/agent/rag_agent.py')
path.write_text(content, encoding='utf-8')
print(f'rag_agent.py: {len(content.splitlines())} lines')
