import pathlib

content = (
    '# -*- coding: utf-8 -*-\n'
    '"""AURA OS - Chunk 2: Executor Agent.\n'
    '\n'
    'Agente que ejecuta comandos locales y accede a las APIs de AURA.\n'
    'Es el agente que realiza acciones concretas en el sistema.\n'
    '"""\n'
    'from __future__ import annotations\n'
    '\n'
    'import logging\n'
    'import subprocess\n'
    'import time\n'
    'from pathlib import Path\n'
    'from typing import Any, Dict, List, Optional\n'
    '\n'
    'from backend.core.event_bus import CoreEvent, EventType, get_event_bus\n'
    '\n'
    'logger = logging.getLogger("AURA.ExecutorAgent")\n'
    '\n'
    '\n'
    'class ExecutorAgent:\n'
    '    """Agente que ejecuta comandos y acciones en el sistema.\n'
    '\n'
    '    Capacidades:\n'
    '    - Ejecutar comandos del sistema (shell)\n'
    '    - Leer/escribir archivos\n'
    '    - Invocar APIs internas de AURA\n'
    '    - Reportar progreso y resultados\n'
    '    """\n'
    '\n'
    '    def __init__(\n'
    '        self,\n'
    '        event_bus: Optional[Any] = None,\n'
    '        agent_id: str = "executor_agent",\n'
    '        allowed_commands: Optional[List[str]] = None,\n'
    '    ) -> None:\n'
    '        self._bus = event_bus or get_event_bus()\n'
    '        self._agent_id = agent_id\n'
    '        self._allowed_commands = allowed_commands or [\n'
    '            "ls", "pwd", "echo", "cat", "head", "tail",\n'
    '            "find", "grep", "wc", "mkdir", "touch",\n'
    '        ]\n'
    '        self._execution_count: int = 0\n'
    '        self._last_result: Optional[Dict[str, Any]] = None\n'
    '\n'
    '    def execute_command(\n'
    '        self,\n'
    '        command: str,\n'
    '        args: Optional[List[str]] = None,\n'
    '        timeout: int = 30,\n'
    '        session_id: str = "default",\n'
    '    ) -> Dict[str, Any]:\n'
    '        """Ejecuta un comando del sistema.\n'
    '\n'
    '        Args:\n'
    '            command: Comando a ejecutar\n'
    '            args: Argumentos adicionales\n'
    '            timeout: Tiempo maximo de espera en segundos\n'
    '            session_id: ID de sesion para tracking\n'
    '\n'
    '        Returns:\n'
    '            Dict con resultado, stdout, stderr, exit_code\n'
    '        """\n'
    '        start_time = time.time()\n'
    '        self._execution_count += 1\n'
    '\n'
    '        # Validar comando\n'
    '        cmd_parts = command.split()\n'
    '        if not cmd_parts:\n'
    '            return {\n'
    '                "success": False,\n'
    '                "error": "Comando vacio",\n'
    '                "command": command,\n'
    '                "session_id": session_id,\n'
    '                "agent_id": self._agent_id,\n'
    '                "execution_time_ms": 0,\n'
    '            }\n'
    '\n'
    '        base_cmd = cmd_parts[0]\n'
    '        if base_cmd not in self._allowed_commands:\n'
    '            logger.warning(f"ExecutorAgent: Comando no permitido: {base_cmd}")\n'
    '            return {\n'
    '                "success": False,\n'
    '                "error": f"Comando no permitido: {base_cmd}",\n'
    '                "command": command,\n'
    '                "session_id": session_id,\n'
    '                "agent_id": self._agent_id,\n'
    '                "execution_time_ms": round((time.time() - start_time) * 1000, 2),\n'
    '            }\n'
    '\n'
    '        # Emitir evento de inicio\n'
    '        self._bus.emit(CoreEvent(\n'
    '            type=EventType.ACTION,\n'
    '            data={\n'
    '                "command": command,\n'
    '                "args": args or [],\n'
    '                "session_id": session_id,\n'
    '                "agent_id": self._agent_id,\n'
    '            },\n'
    '            agent=self._agent_id,\n'
    '            status="running",\n'
    '        ))\n'
    '\n'
    '        try:\n'
    '            cmd_args = [command] + (args or [])\n'
    '            result = subprocess.run(\n'
    '                cmd_args,\n'
    '                capture_output=True,\n'
    '                text=True,\n'
    '                timeout=timeout,\n'
    '                cwd=Path.cwd(),\n'
    '            )\n'
    '\n'
    '            execution_time = round((time.time() - start_time) * 1000, 2)\n'
    '            success = result.returncode == 0\n'
    '\n'
    '            self._last_result = {\n'
    '                "success": success,\n'
    '                "command": command,\n'
    '                "args": args or [],\n'
    '                "stdout": result.stdout,\n'
    '                "stderr": result.stderr,\n'
    '                "exit_code": result.returncode,\n'
    '                "execution_time_ms": execution_time,\n'
    '                "session_id": session_id,\n'
    '                "agent_id": self._agent_id,\n'
    '            }\n'
    '\n'
    '            # Emitir evento de resultado\n'
    '            self._bus.emit(CoreEvent(\n'
    '                type=EventType.RESULT,\n'
    '                data=self._last_result,\n'
    '                agent=self._agent_id,\n'
    '                status="completed" if success else "failed",\n'
    '            ))\n'
    '\n'
    '            logger.info(f"ExecutorAgent: Comando ejecutado: {command} ({"OK" if success else "FAIL"})")\n'
    '            return self._last_result\n'
    '\n'
    '        except subprocess.TimeoutExpired:\n'
    '            execution_time = round((time.time() - start_time) * 1000, 2)\n'
    '            error_result = {\n'
    '                "success": False,\n'
    '                "command": command,\n'
    '                "args": args or [],\n'
    '                "stdout": "",\n'
    '                "stderr": f"Timeout después de {timeout}s",\n'
    '                "exit_code": -1,\n'
    '                "execution_time_ms": execution_time,\n'
    '                "session_id": session_id,\n'
    '                "agent_id": self._agent_id,\n'
    '            }\n'
    '            self._last_result = error_result\n'
    '            self._bus.emit(CoreEvent(\n'
    '                type=EventType.ERROR,\n'
    '                data=error_result,\n'
    '                agent=self._agent_id,\n'
    '                status="failed",\n'
    '            ))\n'
    '            logger.error(f"ExecutorAgent: Timeout en comando: {command}")\n'
    '            return error_result\n'
    '\n'
    '        except Exception as e:\n'
    '            execution_time = round((time.time() - start_time) * 1000, 2)\n'
    '            error_result = {\n'
    '                "success": False,\n'
    '                "command": command,\n'
    '                "args": args or [],\n'
    '                "stdout": "",\n'
    '                "stderr": str(e),\n'
    '                "exit_code": -1,\n'
    '                "execution_time_ms": execution_time,\n'
    '                "session_id": session_id,\n'
    '                "agent_id": self._agent_id,\n'
    '            }\n'
    '            self._last_result = error_result\n'
    '            self._bus.emit(CoreEvent(\n'
    '                type=EventType.ERROR,\n'
    '                data=error_result,\n'
    '                agent=self._agent_id,\n'
    '                status="failed",\n'
    '            ))\n'
    '            logger.error(f"ExecutorAgent: Error ejecutando comando: {e}")\n'
    '            return error_result\n'
    '\n'
    '    def get_status(self) -> Dict[str, Any]:\n'
    '        """Retorna estado del agente."""\n'
    '        return {\n'
    '            "agent_id": self._agent_id,\n'
    '            "execution_count": self._execution_count,\n'
    '            "last_result": self._last_result,\n'
    '            "allowed_commands": self._allowed_commands,\n'
    '        }\n'
    '\n'
    '    def add_allowed_command(self, command: str) -> None:\n'
    '        """Agrega un comando permitido al whitelist."""\n'
    '        if command not in self._allowed_commands:\n'
    '            self.
