# /etc/pacman.conf de AURA OS Custom
# Repositorios para la distro personalizada

[options]
HoldPkg = pacman glibc
Architecture = auto
CheckSpace
SigLevel = Required DatabaseOptional
LocalFileSigLevel = Optional
Locale = en_US.UTF-8

[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist

[community]
Include = /etc/pacman.d/mirrorlist

[multilib]
Include = /etc/pacman.d/mirrorlist

# Repositorios adicionales
[archlinuxhacking]
SigLevel = Optional TrustAll
Server = https://repo.archlinuxhacking.org/$arch

[blackarch]
SigLevel = Optional TrustAll
Server = https://repo.blackarch.org/blackarch/$repo
