#!/usr/bin/env python3
"""CI gate: fail the build when any ARIA OS version copy drifts from pyproject.toml.

``pyproject.toml`` is the single source of truth. Everything else is generated by
``tools/sync_version.py``; this script is the enforcement half of that contract
and is wired into ``.github/workflows/version-check.yml``.

It is read-only by design — CI must never be able to "fix" a drifted version by
writing to the tree, or the gate becomes a no-op that always passes.

Exit codes: ``0`` consistent, ``1`` drift, ``2`` configuration error.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from version_manifest import (  # noqa: E402
    FROZEN_TARGETS,
    MANAGED_TARGETS,
    REPO_ROOT,
    canonical_version,
    extract,
)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--verbose", action="store_true", help="also list the frozen targets"
    )
    args = parser.parse_args(argv)

    try:
        version = canonical_version()
    except SystemExit as exc:
        print(f"ERROR {exc}", file=sys.stderr)
        return 2

    print(f"Canonical version (pyproject.toml): {version}\n")

    problems: list[str] = []

    for target in MANAGED_TARGETS:
        full = REPO_ROOT / target.path
        label = f"{target.path} ({target.label})"

        if not full.exists():
            if target.required:
                problems.append(f"{label}: MISSING_FILE — managed file not found")
                print(f"FAIL  {label}: MISSING_FILE")
            else:
                print(f"SKIP  {label}: not present")
            continue

        try:
            found = extract(target, full.read_text(encoding="utf-8"))
        except Exception as exc:  # noqa: BLE001
            problems.append(f"{label}: {exc}")
            print(f"FAIL  {label}: {exc}")
            continue

        if not found:
            if target.required:
                problems.append(f"{label}: NOT_FOUND — no version literal matched")
                print(f"FAIL  {label}: NOT_FOUND")
            else:
                print(f"SKIP  {label}: optional, no literal present")
            continue

        current = found[0]
        extra = f" (+{len(found) - 1} more literal(s) in file)" if len(found) > 1 else ""
        if current == version:
            print(f"OK    {label}: {current}{extra}")
        else:
            problems.append(f"{label}: MISMATCH found {current!r}, expected {version!r}")
            print(f"FAIL  {label}: {current!r} != {version!r}{extra}")

    print()
    if problems:
        print(f"Version drift detected: {len(problems)} problem(s)")
        for problem in problems:
            print(f"  - {problem}")
        print("\nFix with: python tools/sync_version.py")
        return 1

    if args.verbose:
        print("Frozen (intentionally not managed):")
        for path, reason in FROZEN_TARGETS:
            print(f"  - {path}: {reason}")
        print()

    print(f"All managed locations match canonical version {version}.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
